"""
Training loop for ImprovedGCN using margin-based loss with negative sampling.

Negative samples are generated by randomly corrupting the head or tail entity
of each positive relation triple.
"""
from __future__ import annotations

import random
from typing import List, Optional, Tuple

import torch
import torch.nn as nn
import torch.optim as optim

from src.data.tkg_dataset import RelationTriple, TKGDataset
from src.models.improved_gcn import ImprovedGCN


def _corrupt_triple(
    triple: RelationTriple,
    num_entities: int,
    corrupt_head: bool,
) -> Tuple[int, int, int]:
    """Replace head or tail with a random entity."""
    if corrupt_head:
        return (random.randint(0, num_entities - 1), triple.relation, triple.tail)
    else:
        return (triple.head, triple.relation, random.randint(0, num_entities - 1))


def _score_triples(
    heads: torch.Tensor,     # [B] entity ids
    tails: torch.Tensor,     # [B] entity ids
    H: torch.Tensor,         # [N, d] all embeddings
) -> torch.Tensor:           # [B]
    """
    TransE-style scoring: -||h + r - t||  (we omit r here; the GCN
    already encodes relational context into entity embeddings).
    Using negative L2 distance between head and tail embeddings as proxy.
    """
    h_emb = H[heads]   # [B, d]
    t_emb = H[tails]   # [B, d]
    return -torch.norm(h_emb - t_emb, p=2, dim=1)   # [B]  higher = more plausible


class GCNTrainer:
    """
    Wraps ImprovedGCN with a training loop.

    Loss: margin ranking loss
        L = Σ max(0, γ - score(pos) + score(neg))
    """

    def __init__(
        self,
        model: ImprovedGCN,
        dataset: TKGDataset,
        margin: float = 1.0,
        lr: float = 1e-3,
        device: Optional[torch.device] = None,
    ) -> None:
        self.model = model
        self.dataset = dataset
        self.margin = margin
        self.device = device or torch.device("cpu")
        self.model.to(self.device)
        self.optimizer = optim.Adam(model.parameters(), lr=lr)

    def _sample_batch(
        self,
        triples: List[RelationTriple],
        batch_size: int,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Returns (pos_heads, pos_tails, neg_heads, neg_tails) each [batch_size].
        """
        batch = random.sample(triples, min(batch_size, len(triples)))
        N = self.dataset.num_entities

        pos_h, pos_t, neg_h, neg_t = [], [], [], []
        for triple in batch:
            pos_h.append(triple.head)
            pos_t.append(triple.tail)
            corrupt_head = random.random() < 0.5
            nh, nr, nt = _corrupt_triple(triple, N, corrupt_head)
            neg_h.append(nh)
            neg_t.append(nt)

        to_t = lambda lst: torch.tensor(lst, dtype=torch.long, device=self.device)
        return to_t(pos_h), to_t(pos_t), to_t(neg_h), to_t(neg_t)

    def train_epoch(self, batch_size: int = 256) -> float:
        """Run one epoch; returns mean loss."""
        self.model.train()
        triples = self.dataset.relation_triples
        if not triples:
            return 0.0

        total_loss = 0.0
        num_batches = max(len(triples) // batch_size, 1)

        for _ in range(num_batches):
            self.optimizer.zero_grad()
            H = self.model()                          # [N, d]

            pos_h, pos_t, neg_h, neg_t = self._sample_batch(triples, batch_size)
            pos_score = _score_triples(pos_h, pos_t, H)   # [B]
            neg_score = _score_triples(neg_h, neg_t, H)   # [B]

            loss = torch.clamp(self.margin - pos_score + neg_score, min=0.0).mean()
            loss.backward()
            self.optimizer.step()
            total_loss += loss.item()

        return total_loss / num_batches

    def fit(
        self,
        epochs: int = 50,
        batch_size: int = 256,
        log_every: int = 10,
    ) -> List[float]:
        losses = []
        for epoch in range(1, epochs + 1):
            loss = self.train_epoch(batch_size)
            losses.append(loss)
            if epoch % log_every == 0:
                print(f"Epoch {epoch:4d}/{epochs}  loss={loss:.4f}")
        return losses
